profile: null
region: ap-northeast-1
versioning: false
default_alias: null
clean_build: false
configuration:
  name: lambda-functions
  runtime: python2.7
  role: {{ env['AWS_LAMBDA_ROLE'] }}
  handler: check_github_activity.lambda_handler
  description: This is a sample lambda function.
  timeout: 10
  memory_size: 128
  environment_variables:
    GITHUB_USER: {{ env['GITHUB_USER'] }}
    GITHUB_LOGIN_USER: {{ env['GITHUB_LOGIN_USER'] }}
