key_id: {{ env['AWS_KMS_KEY_ID'] }}
cipher_texts:
  GITHUB_LOGIN_PASSWORD: AQECAHgOIPnzPYQ6iV6xjqR9krIKOJepnv7ugGoaZGpC1Suh5gAAAHIwcAYJKoZIhvcNAQcGoGMwYQIBADBcBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDEMFRDg5c8wiy1wghwIBEIAvxOL8RxoDxHOsRHP5u7LiUoMdErZ9ckIYKYiExVobVUl8LvrYgTRoAXt4ccYtoX4=
  SLACK_WEBHOOK_URL: AQECAHgOIPnzPYQ6iV6xjqR9krIKOJepnv7ugGoaZGpC1Suh5gAAAK8wgawGCSqGSIb3DQEHBqCBnjCBmwIBADCBlQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzZQhB7F5cjHOcfA3QCARCAaHqmBLDy1ShKvrQJNk50E/5X6ueWT65fvka8scnOnuNHUc1aeTonHnCdSFOFy6qHUeNiD3zxu7dDvBdv2gyjJCGRQzi7M/5jDFqoVsWuwRORtcYvcxCDUS3Lo0gkO6GgZxnVeDkTNISh
