rules:
- name: check_github_activity
  description: check_github_activity
  schedule: cron(0 12 * * ? *)
  targets:
  - id: check_github_activity
    input:
      this:
      - is: a
      - sample: input
